export const PRODUCT_CARD_ITEM = [
  {
    price: "500,000",
    image: "/marketplace/product1.png",
    title: "GreenPX Mini",
    capacity: "1 KVA",
    batteryCapacity: "2kW Lithium-Ion Battery",
    solarCapacity: "600W Solar Panel",
    runtime: "6-8 Hours On Full Charge",
    categories: [
      "Internet Router",
      "Decoder",
      "Monitor",
      "Sound System",
      "TV",
      "Refrigerator",
      "Blender",
      "Mobile Phones",
      "HouseHold Items",
      "Lightning",
      "Fans",
    ],
  },
  {
    price: "600,000",
    image: "/marketplace/product2.png",
    title: "GreenPX Midi",
    capacity: "1.5 KVA",
    batteryCapacity: "2.5kW Lithium-Ion Battery",
    solarCapacity: "800W Solar Panel",
    runtime: "5-8 Hours On Full Charge",
    categories: [
      "Decoder",
      "Sound System",
      "Mobile Phones",
      "TV",
      "Refrigerator",
      "Monitor",
      "HouseHold Items",
      "Lightning",
      "Internet Router",
      "Fans",
      "Blender",
    ],
  },
  {
    price: "800,000",
    image: "/marketplace/product3.png",
    title: "GreenPX Maxi",
    capacity: "2 KVA",
    batteryCapacity: "3kW Lithium-Ion Battery",
    solarCapacity: "1000W Solar Panel",
    runtime: "4-8 Hours On Full Charge",
    categories: [
      "Monitor",
      "Mobile Phones",
      "Fans",
      "Blender",
      "Lightning",
      "Sound System",
      "TV",
      "Internet Router",
      "Refrigerator",
      "HouseHold Items",
      "Decoder",
    ],
  },
];
