import { Product } from "./ProductDetails";

export const PRODUCT_CARD_ITEM: Product[] = [
  // greenpx-mini
  {
    slug: "greenpx-mini",
    price: "500,000",
    availability: "In stock",
    usage: "Perfect for small homes, students, and light appliance users",
    title: "GreenPX Mini",
    capacity: "1 KVA",
    whatsappLink: "https://wa.link/zo13js",
    batteryCapacity: "1,000W Lithium-Ion Battery",
    solarCapacity: "600W Solar Panel",
    runtime: "6-8 Hours On Full Charge",
    warranty: "3 Years Warranty",
    images: [
      "/marketplace/greenpx-maxi.png",
      "/marketplace/px1.png",
      "/marketplace/px2.png",
      "/marketplace/px3.png",
      "/marketplace/px4.png",
    ],
    description:
      "The GreenPX Mini is your go-to portable solar power solution for light energy needs. Whether you’re powering your fan, lights, or television, the Mini offers dependable off-grid energy wrapped in a compact, easy-to-use system. Perfect for students, small households, or as a backup for essential devices.",
    categories: [
      "TV",
      "Laptop",
      "Monitor",
      "Mobile Phones",
      "Lightning",
      "Mobile Phones",
      "Decoder",
      "Fans",
      "Internet Router",
    ],
    specifications: [
      "Power Output: 400W (2x 200W Monocrystalline Panels)",
      "Battery: 1,000Wh Lithium-ion Battery",
      "Charging Adapter: 24V / 3A AC Adapter (Wall charging)",
      "DC Ports: 1 x DC Input, 2 x Dc Output",
      "USB Ports: 2 x USB-A (5V, 3A)",
      "Display: Digital Display for battery and usage status",
      "Backup Duration: 8-10+ hours on average load",
    ],
    features: [
      "Plug-and-Play Setup",
      "Pure Sine Wave Output",
      "Noise-Free Operation",
      "Digital Monitoring Display",
      "Solar/PHCN Charging Options",
      "Safe, Durable & Easy to Move",
      "Eco-friendly with zero emissions",
    ],
    reviews: {
      total: 2400,
      averageRating: 4.8,
      ratings: [
        {
          name: "Micheal O.",
          avatar: "/marketplace/Michael.png",
          date: "28/10/2021",
          rating: 5,
          review:
            "I run a small restaurant, and now I can keep my fridge and essential appliances running smoothly without relying on the unstable grid. It’s powerful, reliable, and cost-effective",
        },
        {
          name: "Chinwe A.",
          avatar: "/marketplace/Chinwe.png",
          date: "18/09/2020",
          rating: 5,
          review:
            "My home now has stable electricity throughout the night. It powers my fridge, fans, TV, and lights without any issues. The best part is that I don’t have to worry about fuel or noise like with my old generator",
        },
        {
          name: "Abdullahi K.",
          avatar: "/marketplace/Abdullahi.png",
          date: "15/08/2024",
          rating: 5,
          review:
            "As a shop owner, I need electricity for my display lights, POS machine, and fridge. GreenPX gives me all the power I need without extra costs on fuel. It’s an excellent investment for any business",
        },
      ],
    },
  },

  // greenpx-midi
  {
    slug: "greenpx-midi",
    price: "600,000",
    availability: "In stock",
    usage: "Best fit for small businesses and moderate energy users",
    title: "GreenPX Midi",
    capacity: "1.5 KVA",
    whatsappLink: "https://wa.link/zo13js",
    batteryCapacity: "1,500W Lithium-Ion Battery",
    solarCapacity: "800W Solar Panel",
    runtime: "5-8 Hours On Full Charge",
    warranty: "3 Years Warranty",
    images: [
      "/marketplace/px-midi.jpg",
      "/marketplace/px1.webp",
      "/marketplace/px-midi2.jpg",
      "/marketplace/px3.jpg",
      "/marketplace/px4.webp",
    ],
    description:
      "The GreenPX Midi is a powerful mid-tier solar generator built for convenience, performance, and everyday energy needs. It offers the perfect balance between the lightweight GreenPX Mini and the heavy-duty Maxi. Whether you’re powering your home office or keeping your essential appliances running, the Midi is your dependable companion for clean and silent energy.",
    categories: [
      "TV",
      "Laptop",
      "Monitor",
      "HouseHold Items",
      "Sound System",
      "Lightning",
      "Mobile Phones",
      "Decoder",
      "Fans",
      "Internet Router",
      "Basic Office Equipment",
      "Small Printers",
    ],
    specifications: [
      "Model: Midi1000",
      "Rated Battery Power: 2,500W",
      "Rated Capacity: 1KVA",
      "DC Input Voltage: 12-24V",
      "DC Input Current: 5-7A",
      "AC Output Voltage: 230V",
      "AC Output Frequency: 50Hz",
      "PV Input Voltage: 160-180V",
      "Maximum PV Input Power: 800W",
      "Battery Type: LiFePO4",
      "Operating Temperature Range: 0-45°C",
      "Operating Humidity Range: <95%",
      "Dimension (W x H x D): 23 x 33 x 41 cm",
      "Weight: 14kg",
    ],

    features: [
      "Plug-and-Play Setup",
      "Pure Sine Wave Output",
      "Noise-Free Operation",
      "Digital Monitoring Display",
      "Solar/PHCN Charging Options",
      "Safe, Durable & Easy to Move",
      "Eco-friendly with zero emissions",
    ],
    reviews: {
      total: 2400,
      averageRating: 4.8,
      ratings: [
        {
          name: "Micheal O.",
          avatar: "/marketplace/Michael.png",
          date: "28/10/2021",
          rating: 5,
          review:
            "I run a small restaurant, and now I can keep my fridge and essential appliances running smoothly without relying on the unstable grid. It’s powerful, reliable, and cost-effective",
        },
        {
          name: "Chinwe A.",
          avatar: "/marketplace/Chinwe.png",
          date: "18/09/2020",
          rating: 5,
          review:
            "My home now has stable electricity throughout the night. It powers my fridge, fans, TV, and lights without any issues. The best part is that I don’t have to worry about fuel or noise like with my old generator",
        },
        {
          name: "Abdullahi K.",
          avatar: "/marketplace/Abdullahi.png",
          date: "15/08/2024",
          rating: 5,
          review:
            "As a shop owner, I need electricity for my display lights, POS machine, and fridge. GreenPX gives me all the power I need without extra costs on fuel. It’s an excellent investment for any business",
        },
      ],
    },
  },

  // greenpx-maxi
  {
    slug: "greenpx-maxi",
    price: "800,000",
    availability: "In stock",
    usage:
      "Designed for heavier usage. Suitable for offices, homes and outdoor activities",
    title: "GreenPX Maxi",
    capacity: "2 KVA",
    whatsappLink: "https://wa.link/zo13js",
    batteryCapacity: "2,000W Lithium-Ion Battery",
    solarCapacity: "1000W Solar Panel",
    runtime: "4-8 Hours On Full Charge",
    warranty: "3 Years Warranty",
    images: [
      "/marketplace/greenpx-maxi.png",
      "/marketplace/px1.png",
      "/marketplace/px2.png",
      "/marketplace/px3.png",
      "/marketplace/px4.png",
    ],
    description:
      "The GreenPX Maxi is your ultimate solar power companion, crafted to meet the needs of modern households and businesses. Built for high performance, durability, and ease of use, this unit is perfect for anyone tired of erratic power supply and looking for a cleaner, quieter, and more reliable solution.+Whether you’re preserving food in a deep freezer or keeping your home office powered through the night, the GreenPX Maxi is built to deliver.",
    categories: [
      "TV",
      "Monitor",
      "HouseHold Items",
      "Mobile Phones",
      "Sound System",
      "Lightning",
      "Mobile Phones",
      "Decoder",
      "Fans",
      "Internet Router",
      "Refrigerator",
      "Freezer",
      "Blender",
      "Printers",
      "Office Appliances",
    ],
    specifications: [
      "Power Output: 920W (2x 460W Monocrystalline Panels)",
      "Battery: 2,000Wh Lithium-ion Battery",
      "Inverter Capacity: 2kVA",
      "Charging Adapter: 24V / 6A AC Adapter (Wall charging)",
      "DC Ports: 1 x DC Input, 2 x Dc Output",
      "USB Ports: 2 x USB-A (5V, 3A)",
      "Display: Digital Display for battery and usage status",
      "Backup Duration: 8-10+ hours on average load",
    ],
    features: [
      "Plug-and-Play Setup",
      "Pure Sine Wave Output",
      "Noise-Free Operation",
      "Digital Monitoring Display",
      "Solar/PHCN Charging Options",
      "Safe, Durable & Easy to Move",
      "Eco-friendly with zero emissions",
    ],
    reviews: {
      total: 2400,
      averageRating: 4.8,
      ratings: [
        {
          name: "Micheal O.",
          avatar: "/marketplace/Michael.png",
          date: "28/10/2021",
          rating: 5,
          review:
            "I run a small restaurant, and now I can keep my fridge and essential appliances running smoothly without relying on the unstable grid. It’s powerful, reliable, and cost-effective",
        },
        {
          name: "Chinwe A.",
          avatar: "/marketplace/Chinwe.png",
          date: "18/09/2020",
          rating: 5,
          review:
            "My home now has stable electricity throughout the night. It powers my fridge, fans, TV, and lights without any issues. The best part is that I don’t have to worry about fuel or noise like with my old generator",
        },
        {
          name: "Abdullahi K.",
          avatar: "/marketplace/Abdullahi.png",
          date: "15/08/2024",
          rating: 5,
          review:
            "As a shop owner, I need electricity for my display lights, POS machine, and fridge. GreenPX gives me all the power I need without extra costs on fuel. It’s an excellent investment for any business",
        },
      ],
    },
  },
];
