import type { Metadata } from "next";
import "./globals.css";
import { onest, outfit } from "@/lib/fonts";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Green Potentia Limited",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} ${outfit.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
